# Temp directory configuration
java.io.tmpdir=${java.io.tmpdir}

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=adilaquil2005@gmail.com
spring.mail.password=eycb ysfv sdjd ikmh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
app.upload.dir=./uploads

# Default admin account
app.admin.email=admin@vitalislink.com
app.admin.password=admin123

# H2 Console (optional, for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console